// Generated by https://quicktype.io

export interface CompanySales {
	dataUser: DataUser;
	avatar: string;
	createdDate: number;
	idRol: string;
	id: string;
	email: string;
	idUserCreate: string;
	state: boolean;
}

export interface DataUser {
	youtube: string;
	ruc: string;
	web: string;
	phone: string;
	facebook: string;
	businessName: string;
	description: string;
	linkedin: string;
	email: string;
	rol: string;
}
