// Generated by https://quicktype.io

export interface PostJob {
	title: string;
	description: string;
	modality: string;
	timeEstimated: string;
	salaryRange: string;
	funtionsPost: string;
	idCategory: string;
	idPosition: string;
	idSkills: string[];
	location: string;
	priority: number;
	typePost:number
}
