// Generated by https://quicktype.io

export interface Project {
	_id: string;
	title: string;
	descriptionPost: string;
	funtionsPost: string;
	priority: number;
	location: string;
	modality: string;
	idCategory: string;
	idPosition: string;
	idCompany: string;
	idsSkillsPostJob: string[];
	salaryRange: string;
	timeEstimated: string;
	state: boolean;
	createdDate: number;
	updateDate: number;
}
